
axis_linear: 1
axis_angular: 3

scale_linear: 0.7
scale_angular: 0.7

#scale_linear_turbo: 0.89
scale_linear_turbo: 1.0
scale_angular_turbo: 1.0
enable_button: 5  # L2 shoulder button
enable_turbo_button: -1  # L1 shoulder button
