#axis_linear: 1
#axis_angular: 0

#scale_linear: 1.0
#scale_angular: 0.436

#scale_linear_turbo: 0.89
#scale_linear_turbo: 0.75
#enable_button: 0  # L2 shoulder button
#enable_turbo_button: 1  # L1 shoulder button

axis_linear: 1
axis_angular: 2

scale_linear: 2.0
scale_angular: 0.6

#scale_linear_turbo: 0.89
scale_linear_turbo: 2.0
enable_button: 4  # L2 shoulder button
enable_turbo_button: 1  # L1 shoulder button
