joints: ['joint_1','joint_2', 'joint_3', 'joint_4']
joint_1:
  controller:
    package: dynamixel_controllers
    module: joint_position_controller
    type: JointPositionController
  joint_name: joint_1
  joint_max_speed: 2.0
  motor:
    id: 1
    init: 512
    min: 130
    max: 900
joint_2:
  controller:
    package: dynamixel_controllers
    module: joint_position_controller
    type: JointPositionController
  joint_name: joint_2
  joint_max_speed: 2.0
  motor:
    id: 2
    init: 512
    min: 820
    max: 180
joint_3:
  controller:
    package: dynamixel_controllers
    module: joint_position_controller
    type: JointPositionController
  joint_name: joint_3
  joint_max_speed: 2.0
  motor:
    id: 3
    init: 512
    min: 180
    max: 820
joint_4:
  controller:
    package: dynamixel_controllers
    module: joint_position_controller
    type: JointPositionController
  joint_name: joint_4
  joint_max_speed: 2.0
  motor:
    id: 4
    init: 512
    min: 180
    max: 820


arm_controller:
  controller:
    package: dynamixel_controllers
    module: joint_trajectory_action_controller
    type: JointTrajectoryActionController
  joint_trajectory_action_node: 
    min_velocity: 0.1
    constraints:
         goal_time: 0.1
